# Generated by Django 4.0.3 on 2022-03-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('isbn', models.IntegerField(verbose_name='ISBN')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtítulo')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Fecha publicación')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('category', models.CharField(choices=[('dulce', 'recetas dulces'), ('salado', 'snacks salados'), ('postres', 'postrecitos ricos')], max_length=100, verbose_name='Categoría')),
            ],
        ),
    ]
