# Generated by Django 4.0.3 on 2022-03-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation',
            field=models.TextField(default='', verbose_name='Preparación'),
        ),
    ]
