# Generated by Django 4.0.3 on 2022-03-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, choices=[('dulce', 'recetas dulces'), ('salado', 'snacks salados'), ('postres', 'postrecitos ricos'), ('-', 'sin categoría')], default='-', max_length=100, verbose_name='Categoría'),
        ),
    ]
